Update and rename lynis-devkit to leenus-devkit

diff --git a/leenus-devkit b/leenus-devkit
--- a/leenus-devkit
+++ b/leenus-devkit
@@ -10,7 +10,7 @@ VERBOSE=0
 DEVKIT_RELEASE="20201005"
 DEVKIT_VERSION="1.0.6"
 
-# Lynis variables
+# Leenus variables
 SHOW_WARNINGS_ONLY=0
 LOGTEXT=1
 QUIET=0
@@ -19,30 +19,30 @@ ECHOCMD="echo"
 YELLOW=""
 NORMAL=""
 SECTION="${YELLOW}"
-LOGFILE="./lynis-dev.log"
+LOGFILE="./leenus-dev.log"
 DISPLAY_LANG="$LANG"
 
 if [ "${MY_USER_ID}" = "0" ]; then echo "Do not run this as root"; exit 1; fi
 if [ ! -f "${CONFIG_FILE}" ]; then echo "Could not open config file: ${CONFIG_FILE}"; exit 1; fi
 
 CHECK_VERBOSE=$(awk -F= '/^verbose=/ { print $2 }' ${CONFIG_FILE} | egrep -i "yes") && VERBOSE=1
-LYNIS_PATH=$(awk -F= '/^lynis-directory=/ { print $2 }' ${CONFIG_FILE})
-if [ "${LYNIS_PATH}" = "" -o ! -d "${LYNIS_PATH}" ]; then echo "Could not find the Lynis directory"; exit 1; fi
+LEENUS_PATH=$(awk -F= '/^leenus-directory=/ { print $2 }' ${CONFIG_FILE})
+if [ "${LEENUS_PATH}" = "" -o ! -d "${LEENUS_PATH}" ]; then echo "Could not find the Leenus directory"; exit 1; fi
 
 
-if [ ! -f ${LYNIS_PATH}/lynis ]; then echo "Could not find Lynis (tried: ${LYNIS_PATH}/lynis)"; exit 1; fi
-LYNIS_VERSION=$(grep "PROGRAM_VERSION=" ${LYNIS_PATH}/lynis | awk -F= '{print $2}' | sed 's/"//g')
+if [ ! -f ${LEENUS_PATH}/leenus ]; then echo "Could not find Leenus (tried: ${LEENUS_PATH}/leenus)"; exit 1; fi
+LEENUS_VERSION=$(grep "PROGRAM_VERSION=" ${LEENUS_PATH}/leenus | awk -F= '{print $2}' | sed 's/"//g')
 
 
 
 echo "======================================================================"
 echo "Development kit:        ${DEVKIT_VERSION} [${DEVKIT_RELEASE}]"
-echo "Lynis directory:        ${LYNIS_PATH}"
-echo "Lynis version:          ${LYNIS_VERSION}"
+echo "Leenus directory:        ${LEENUS_PATH}"
+echo "Leenus version:          ${LEENUS_VERSION}"
 echo "Verbose:                $VERBOSE"
 echo "======================================================================"
 
-FUNCTIONS_FILE="${LYNIS_PATH}/include/functions"
+FUNCTIONS_FILE="${LEENUS_PATH}/include/functions"
 if [ -f "${FUNCTIONS_FILE}" ]; then
     . ${FUNCTIONS_FILE}
 fi
